de:
  kursplan: kurse.php
  programm: 
    - kalender.php
    - zeichenerklaerung.php
  tickets: tickets.php
  lehrer: 
    - lehrer-krs.php
    - lehrer-pro.php
    - lehrer.php
  kuenstler: kuenstler.php
  agbs: agb.php
  workshop_programm: workshops.php
  workshop_anmeldung: ws-anmeldung.php
  dance_intensive_programm: 
    - 'ausbildung.php?vwbdid=1&l=1'
    - ausbildung.php
    - ausbildung_index.php
  profitraining: profitraining.php
  contact_jam: contact_jam.php
  studios: raeume.php
  vermietungsinfo: vermietung.php
  profil_partner: 
    - profil.php
    - partner.php
  root: news.php
  apap_netzwerk: apap.php
  kontakt: 
    - kontakt.php
    - kontakt_anfahrt.php
en:
  agbs: agb-en.php
